# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mysql://121.4.56.97:3306/quartz?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456